administratorapp/urls.py
from django.urls import path
from . import views
from administratorapp.views import *
from django.contrib.auth.decorators import login_required

app_name = 'administratorapp'
urlpatterns = [
    path('managerlist', login_required(ManagerList.as_view()), name='managerlist'),
    path('managerlist/<int:user_id>/activeuser', login_required(ActiveUser.as_view()), name='activeuser'),
]

cloitLMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('learning/', include('learningapp.urls')),
    path('', include('managementapp.urls')),
    path('adm/', include('administratorapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administratorapp/models.py
from django.db import models

# Create your models here.

administratorapp/forms.py
from examapp.models import Upload
from django import forms
from .models import *

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Upload
        fields = ('description', 'document', )
        labels = {'description': 'Имя файла', 'document': 'Файл'}

administratorapp/views.py
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.views.generic import ListView, DetailView, CreateView, TemplateView, View
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render, redirect
from django.contrib import messages
from examapp.models import *
from learningapp.models import LearningQuizAttempt, QuestionСoefficient, LearningQuizAttemptQuestions
from managementapp.models import Subscription
from django.template.defaulttags import register
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Q
from openpyxl import load_workbook, Workbook

@register.filter
def count(value):
    return Question.objects.filter(status__id = 1, questions_bank__in = value).count()

@register.filter
def get_saler(value):
    print(User.objects.filter(username = value).values('groups__name'))
    return value

class CheckAdminPermissions(UserPassesTestMixin):
    
    def test_func(self):
        return True if self.request.user.username == 'admin' else False
    
    def handle_no_permission(self):
        return redirect('managementapp:home')

class CheckStaffPermissions(UserPassesTestMixin):
    
    def test_func(self):
        return self.request.user.is_staff
    
    def handle_no_permission(self):
        return redirect('managementapp:home')

class ManagerList(CheckStaffPermissions, ListView):
    model = User
    paginate_by = 10
    context_object_name = 'object_list'
    template_name = 'administratorapp/managerlist.html'
    
    def get_queryset(self, **kwargs):
        query = self.request.GET.get('search')
        if query == None:
            obj = (
                User.objects
                .filter(groups__name__in = ['manager', 'saler'])
                .select_related('extendinguserfields')
                .order_by('-id')
                )
            return obj
        else:
            obj = (
                User.objects
                .filter(groups__name__in = ['manager', 'saler'])
                .filter(Q(username__icontains = query) | Q(first_name__icontains = query) | Q(last_name__icontains = query) | Q(email__icontains = query) | Q(extendinguserfields__middle_name__icontains = query) | Q(extendinguserfields__department__icontains = query))
                .select_related('extendinguserfields')
                .order_by('-id')
                )
            self.paginate_by = obj.count()
            return obj                

    def post(self, request, *args, **kwargs):
        
        groupe = Group.objects.get(name = 'manager')
        
        if request.POST.get("form_type") == 'add_demo' and request.POST.get('qty') != None:
            
            last_demo_manager = User.objects.filter(username__contains = 'demo-manager').count()

            for i in range(int(request.POST.get('qty'))):

                password = BaseUserManager().make_random_password(length=12, allowed_chars='abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ0123456789')
                
                last_user, create = User.objects.get_or_create(
                    username = str('demo-manager' + str(last_demo_manager + i + 1)),
                    first_name = 'Демо',
                    last_name = 'Доступ',
                    email = '',
                    is_superuser = False,
                    is_staff = False,
                    is_active = True,
                )
                
                if create:
                    last_user.set_password(password)  
                    last_user.save()

                groupe.user_set.add(last_user)

                extend_user, create = ExtendingUserFields.objects.get_or_create(
                    user = last_user,
                    middle_name = '',
                    department = '',
                    password = password,
                )

                Subscription.objects.create(qty = 3, subtype = 'Тренинг ВОТ', manager = last_user)

            return redirect('administratorapp:managerlist')

        if request.POST.get("form_type") == 'add_manager' and request.POST.get('username') != None and request.POST.get('first_name') != None:

            password = BaseUserManager().make_random_password(length=12, allowed_chars='abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ0123456789')

            last_user, create = User.objects.get_or_create(
                username = str(request.POST.get('username')),
                first_name = str(request.POST.get('first_name')),
                last_name = '',
                email = request.POST.get('email'),
                is_superuser = False,
                is_staff = False,
                is_active = True,
            )
            
            if create:
                last_user.set_password(password)  
                last_user.save()

            if request.POST.get('saler'):
                groupe, create = Group.objects.get_or_create(name = 'saler')

            groupe.user_set.add(last_user)

            extend_user, create = ExtendingUserFields.objects.get_or_create(
                user = last_user,
                middle_name = '',
                department = str(request.POST.get('first_name')),
                password = password,
            )
            
            return redirect('administratorapp:managerlist')
        
        if request.POST.get("form_type") == 'add_subs' and request.POST.getlist('checkeduser') != []:
            
            if len(request.POST.getlist('checkeduser')) == 1:
                
                checked_user = User.objects.get(pk = request.POST.getlist('checkeduser')[0])
                
                if request.POST.get('trening'):
                    Subscription.objects.create(qty = int(request.POST.get('trening')), subtype = 'Тренинг ВОТ', manager = checked_user)
                            
                return redirect('administratorapp:managerlist')
            
            elif len(request.POST.getlist('checkeduser')) > 1:
                messages.warning(request, 'Выбирите 1 пользователя!')
                return redirect('administratorapp:managerlist')
        
        if request.POST.get("form_type") == 'report':

            start = request.POST.get('start') + ' 00:00:01'
            end = request.POST.get('end') + ' 23:59:59'

            if end >= start:
                
                checked_users = request.POST.getlist('checkeduser')
                check_all = request.POST.getlist('check_all')

                if checked_users:
                    checked_managers = User.objects.filter(pk__in=checked_users)
                    subs = Subscription.objects.filter(
                        manager__in=checked_managers, 
                        date__range=(start, end)
                    ).select_related('user', 'course', 'user__extendinguserfields')
                elif check_all:
                    subs = Subscription.objects.filter(
                        date__range=(start, end)
                    ).select_related('user', 'course', 'user__extendinguserfields')
                else:
                    return HttpResponseBadRequest()
                
                wb = Workbook()
                ws = wb.active
                ws.append(['Логин', 'Организация', 'Подписка', 'Кол-во', 'Пользователь', 'Курс', 'Дата'])
                for sub in subs:
                    ws.append([
                            sub.manager.username, 
                            sub.manager.first_name, 
                            sub.subtype, 
                            sub.qty, 
                            (sub.user.get_full_name() if sub.user is not None else ''), 
                            (sub.course.name if sub.course is not None else ''), 
                            sub.date,
                    ])
                ws.append(['', '', '', ''])
                ws.append([f'Итого списано подписок: {subs.count()}'])
                response = HttpResponse(content_type='application/vnd.ms-excel')
                response['Content-Disposition'] = 'attachment;filename="report.xlsx"'
                wb.save(response)

                return response           
             
            return redirect('administratorapp:managerlist')
        
        if request.POST.get("form_type") == 'search_btn' and request.POST.get('search') != []:
            
            return HttpResponseRedirect("?search=%s" % request.POST.get('search'))

        if request.POST.get("form_type") == 'update_attempt':
            
            if LearningQuizAttemptQuestions.objects.filter(learningquizattempt = int(request.POST.get('num')), see_question = False).count() == 0:
                if LearningQuizAttemptQuestions.objects.filter(learningquizattempt = int(request.POST.get('num')), see_question = None).count() == 0:
                    q = LearningQuizAttemptQuestions.objects.filter(learningquizattempt = int(request.POST.get('num')), see_question = True).first()
                    q.see_question = None
                    q.save()
                
                q = LearningQuizAttemptQuestions.objects.filter(learningquizattempt = int(request.POST.get('num')), see_question = None).first()
                q.see_question = False
                q.save()
                
                if LearningQuizAttemptQuestions.objects.filter(learningquizattempt = int(request.POST.get('num')), see_question = None).count() == 0:
                    q = LearningQuizAttemptQuestions.objects.filter(learningquizattempt = int(request.POST.get('num')), see_question = True).first()
                    q.see_question = None
                    q.save()

            return redirect('administratorapp:managerlist')
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

class ActiveUser(CheckStaffPermissions, View):

templates/administratorapp/managerlist.html
{% extends 'base manager.html' %}
{% block title %}Список пользователей{% endblock %}
{% load static %}
{% block content %}
<br><br>

<div style="padding-left: 15px; padding-right: 15px;">
<div class="row">
    <div class="column70">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}<br>
        <form method="post" class="multipart/form-data" id='add_subs'>
        {% csrf_token %}
        <input class="search" name="search" type="text" style="max-width: 30%;" placeholder="Поиск...">
        <button type="submit" class="button" name="form_type" value="search_btn">Найти</button>
        <table id="table2" class="text-center" align="center" width="100%">
            <thead>
                <tr>
                    <th style="text-align: center;"><!--<input type="checkbox" name="select-all" id="select-all">--></th>
                    <th style="text-align: center;">Логин</th>
                    <th style="text-align: center;">Имя</th>
                    <th style="text-align: center;">Продавец</th>
                    <th style="text-align: center;">Пароль</th>
                    <th style="text-align: center;">Подписки</th>
                    <th style="text-align: center;">Отключить</th>                    
                </tr>                
            </thead>
            <tbody>
                {% for obj in object_list %}
                    <tr>
                        <td><input type="checkbox" name="checkeduser" value="{{ obj.id }}"></td>
                        <td>{{ obj.username }}</td>
                        <td>{{ obj.first_name}}</td> 
                        <td>
                            {% for group in obj.groups.all %}
                                {% if group.name == 'saler' %}
                                    Это продавец
                                {% elif group.name != 'manager' %}
                                    Создал продавец - {{ group }}
                                {% endif %}
                            {% endfor %}
                        </td>                        
                        <td>{{ obj.extendinguserfields.password }}</td>
                        <td>
                            Подписки: {{ obj|qty_sum }} шт.<br>
                        </td>
                        <td>
                            {% if obj.is_active %}
                                <label class="switch">
                                    <a href="{% url 'administratorapp:activeuser' obj.id %}">
                                    <span class="slider-on"></span>
                                    </a>
                                </label>
                            {% else %}
                                <label class="switch">
                                    <a href="{% url 'administratorapp:activeuser' obj.id %}">
                                    <span class="slider-off"></span>
                                    </a>
                                </label>
                            {% endif %}
                        </td>                        
                    </tr>
                {% endfor %}                
            </tbody>
        </table>
        <div style="text-align: center;">                        
            {% if paginator.count > 10 %}
                <div class="pagination">
                    {% if page_obj.number > 3 %}
                        <a href="?page=1">1</a>
                        {% if page_obj.number > 4 %}
                            <a href="#" style="pointer-events: none; cursor: default;">...</a>
                        {% endif %}
                    {% endif %}
    
                    {% for p in paginator.page_range %}
                        {% if page_obj.number == p %}
                            <a href="?page={{ p }}" class="active">{{ p }}</a>
                        {% elif p > page_obj.number|add:'-3' and p < page_obj.number|add:'3' %}
                            {% if p in checked_page %}
                                <a style="color: black; background-color: #E7E6E7;" href="?page={{ p }}">{{ p }}</a>
                            {% else %}
                                <a href="?page={{ p }}">{{ p }}</a>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
    
                    {% if page_obj.number < paginator.num_pages|add:'-3' %}
                        <a href="#" style="pointer-events: none; cursor: default;">...</a>
                        {% if paginator.num_pages in checked_page %}
                            <a style="color: black; background-color: #E7E6E7;" href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                        {% else %}
                            <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                        {% endif %}
                    {% elif page_obj.number < paginator.num_pages|add:'-2' %}
                        {% if paginator.num_pages in checked_page %}
                            <a style="color: black; background-color: #E7E6E7;" href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                        {% else %}
                            <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                        {% endif %}
                    {% endif %}
                </div>
            {% else %}
                <div class="pagination">
                    {% for p in paginator.page_range %}
                        {% if page_obj.number == p %}
                            <a href="?page={{ p }}" class="active">{{ p }}</a>
                        {% else %}
                            <a href="?page={{ p }}">{{ p }}</a>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
    <div class="column30">
            <div style="text-align: center;">
                <p>Отчет</p>
                <label for="start">С:</label>
                <input type="date" id="start" name="start" value=""><br><br>
                <label for="start">По:</label>
                <input type="date" id="end" name="end" value=""><br><br>
                <input type="checkbox" name="check_all" id="all" value="all"><label for="all">Все Пользователи</label><br><br>
                <button type="submit" name="form_type" value="report" class="button-white">Скачать</button>
            </div>
            <hr>
            <div style="text-align: center;">
                <p>Добавить Подписки</p>
                <input class="input-white" type="text" placeholder="" name="trening" id="trening"><br><br>
                <!-- <input class="input-white" type="text" placeholder="Тренинг" name="trening" id="trening"><br><br>
                <input class="input-white" type="text" placeholder="Тренинг ВОТ" name="treningvot" id="treningvot"><br><br>
                <input class="input-white" type="text" placeholder="Прочие" name="other" id="other"><br><br> -->
                <button type="submit" name="form_type" value="add_subs" class="button-white">Добавить</button>
            </div>
        </form>
        <hr>
        <form method="post" class="multipart/form-data" id='add_manager'>
            {% csrf_token %}
            <div style="text-align: center;">
                <p>Добавить Менеджера</p>
                <input class="input-white" type="text" placeholder="Логин" name="username" id="username"><br><br>
                <input class="input-white" type="text" placeholder="Органицация" name="first_name" id="first_name"><br><br>
                <input class="input-white" type="text" placeholder="Почта" name="email" id="email"><br><br>
                <input type="checkbox" name="saler" id="saler" value="saler"><label for="saler">Продавец</label><br><br>
                <button type="submit" name="form_type" value="add_manager" class="button-white">Создать Менеджера</button>
            </div>
        </form>
        <hr>
        <form method="post" class="multipart/form-data" id='add_demo'>
            {% csrf_token %}
            <div style="text-align: center;">
                <p>Добавить Демо</p>
                <input class="input-white" type="text" placeholder="Кол-во" name="qty" id="qty"><br><br>
                <button type="submit" name="form_type" value="add_demo" class="button-white">Добавить</button>
            </div>
        </form>
        <form method="post" class="multipart/form-data" id='update_attempt'>
            {% csrf_token %}
            <div style="text-align: center;">
                <p>Обновить Тренинг</p>
                <input class="input-white" type="text" placeholder="№ Тренинга" name="num" id="num"><br><br>
                <button type="submit" name="form_type" value="update_attempt" class="button-white">Обновить</button>
            </div>
        </form>
        <hr>        
    </div>
</div>    
</div>

{% endblock %}