cloitLMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('learning/', include('learningapp.urls')),
    path('', include('managementapp.urls')),
    path('adm/', include('administratorapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learningapp/urls.py
from django.urls import path
from . import views
from learningapp.views import *
from django.contrib.auth.decorators import login_required

app_name = 'learningapp'
urlpatterns = [
    path('', login_required(CourseList.as_view()), name='courselist'),
    path('course/<slug:course_slug>', login_required(SelectCourse.as_view()), name='selectcourse'),
    path('course/<slug:course_slug>/lec', login_required(Lections.as_view()), name='lec'),
    path('course/<slug:course_slug>/npa', login_required(Npa.as_view()), name='npa'),
    path('course/<slug:course_slug>/test/<slug:quiz_slug>/<int:quizattempt_id>', login_required(ExamTest.as_view()), name='examtest'),
    path('course/<slug:course_slug>/learning/<slug:quiz_slug>/learning/<int:quizattempt_id>', login_required(LearningTest.as_view()), name='learningtest'),
    path('course/<slug:course_slug>/quizattempts', login_required(QuizAttempts.as_view()), name='quizattempts'),
    path('course/<slug:course_slug>/quizattempts/report/<int:quizattempt_id>', login_required(Report.as_view()), name='report'),
    path('course/<slug:course_slug>/questionslist', login_required(QuestionsList.as_view()), name='questionslist'),
    path('course/<slug:course_slug>/questionslist/<int:question_id>', login_required(SelectQuestion.as_view()), name='selectquestion'),
]

managementapp/urls.py
from django.urls import path
from . import views
from managementapp.views import *
from django.contrib.auth.decorators import login_required

app_name = 'managementapp'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about', views.About, name='about'),
    path('login', LogInView.as_view(), name='login'),
    path('support', Support.as_view(), name='support'),
    path('supportcards', login_required(SupportCards.as_view()), name='supportcards'),
    path('logout', login_required(views.logout_user), name='logout'),
    path('registration', login_required(UsersRegistration.as_view()), name='registration'),
    path('edituser/<int:user_id>', login_required(EditUser.as_view()), name='edituser'),
    path('users', login_required(UsersList.as_view()), name='users'),
    path('managers', login_required(ManagersList.as_view()), name='managers'),
    path('usercourses/<int:user_id>/activeuser', login_required(ActiveUser.as_view()), name='activeuser'),
    path('usercourses/<int:user_id>', login_required(UserCourses.as_view()), name='usercourses'),
    path('usercourses/<int:user_id>/bestreport/<int:course_id>', login_required(BestReport.as_view()), name='bestreport'),
    path('usercourses/<int:user_id>/activecourse/<int:course_id>', login_required(ActiveCourse.as_view()), name='activecourse'),
    path('usercourses/<int:user_id>/deletecourse/<int:course_id>', login_required(DeleteCourse.as_view()), name='deletecourse'),
    path('usercourses/<int:user_id>/activecourse/<int:course_id>/statistics', login_required(CourseStatistics.as_view()), name='statistics'),
    path('addnewuser', login_required(UsersList.as_view()), name='addnewuser'),
    path('usercourse/<int:user_id>/addcourse', login_required(AddCourse.as_view()), name='addcourse'),
]

learningapp/views.py
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect, request, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, TemplateView
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib import messages
from django.urls import reverse
from django.template.defaulttags import register
from datetime import date, datetime, timedelta, timezone
from django.db.models import Sum, Max
from .models import *
from examapp.models import *
from .utils import *
import json
import random
from django.utils.safestring import mark_safe
from openpyxl import load_workbook, Workbook
from cloitLMS.settings import BASE_DIR, MEDIA_ROOT
import os

@register.filter
def question_count(value, curr_user):
    curr_quiz = Quiz.objects.filter(course = value, name__contains = 'Тренинг')
    quizbanks = QuizBankSettings.objects.filter(quiz__in = curr_quiz)
    sum_questions = Question.objects.none()
    for bank in quizbanks:
        if bank.tag.all().first() != None:
            questions = Question.objects.filter(questions_bank__id = bank.bank.id, status = 1, tag__name = bank.tag.all().first())
            sum_questions = sum_questions | questions
        else:
            questions = Question.objects.filter(questions_bank__id = bank.bank.id, status = 1)
            sum_questions = sum_questions | questions
            
    return sum_questions.count()

@register.filter
def quiz_question_count(value):
    return Question.objects.filter(questions_bank = QuizBankSettings.objects.get(quiz = value).bank, status = 1).count()

@register.filter
def sum_qty(x, y):
    return x + y

@register.filter
def report_max_grade(attempt):
    curr_quiz = Quiz.objects.get(pk = attempt.quiz.id)
    if 'Тренинг ' in curr_quiz.name:
        max_grade = LearningQuizAttemptQuestions.objects.filter(learningquizattempt = attempt).count()
    else:
        max_grade = curr_quiz.max_grade
    return max_grade

@register.filter
def percent_result(attempt):
    curr_quiz = Quiz.objects.get(pk = attempt.quiz.id)
    if 'Тренинг ' in curr_quiz.name:
        quotient = attempt.grade / LearningQuizAttemptQuestions.objects.filter(learningquizattempt = attempt).count()
        percent = quotient * 100
    else:
        quotient = attempt.grade / curr_quiz.max_grade
        percent = quotient * 100
    return round(percent)

@register.filter
def percent_learningtest(quiz_slug, user):
    see_questions = QuestionСoefficient.objects.filter(quiz__slug = quiz_slug, user = user, status = 1)
    try:
        quotient = see_questions.exclude(coefficient = None).count() / see_questions.count()
    except:
        quotient = 0
    percent = quotient * 100
    return round(percent)

@register.filter
def get_learning_time(value, user):
    try:
        time = LearningQuizAttemptGrade.objects.filter(
                quiz_attempt__in = LearningQuizAttempt.objects.filter(
                    user = user,
                    quiz__in = Quiz.objects.filter(course = value)
                    )).aggregate(Sum('spend_time'))
        return timedelta(seconds = time['spend_time__sum'])
    except:
        return 0

@register.filter
def get_quiz_learning_time(value, user):
    try:
        time = LearningQuizAttemptGrade.objects.filter(
                quiz_attempt__in = LearningQuizAttempt.objects.filter(
                    user = user,
                    quiz = Quiz.objects.get(name = value)
                    )).aggregate(Sum('spend_time'))
        return timedelta(seconds = time['spend_time__sum'])
    except:
        return 0

def strfdelta(tdelta, fmt):
    d = {"days": tdelta.days}
    d["hours"], rem = divmod(tdelta.seconds, 3600)
    d["minutes"], d["seconds"] = divmod(rem, 60)
    if d["hours"] < 10:
        d["hours"] = '0' + str(d["hours"])
    if d["minutes"] < 10:
        d["minutes"] = '0' + str(d["minutes"])
    if d["seconds"] < 10:
        d["seconds"] = '0' + str(d["seconds"])
    return fmt.format(**d)

@register.filter
def delta(value, arg):
    delta_ressult = value - arg   
    return strfdelta(delta_ressult, "{hours}:{minutes}:{seconds}")

@register.filter
def shuffle(arg):
    my_list = list(arg[:])
    random.shuffle(my_list)
    return my_list

@register.filter
def get_studied_questions(value, user):
    try:
        return QuestionСoefficient.objects.filter(user = user, coefficient__gte = 23, quiz__in = Quiz.objects.filter(course = value, name__contains = 'Тренинг'), status = 1).count()
    except:
        return 0

@register.filter
def get_quiz_studied_questions(value, user):
    try:
        return QuestionСoefficient.objects.filter(user = user, coefficient__gte = 23, quiz = value, status = 1).count()
    except:
        return 0

@register.filter
def get_percent(value, user):
    try:
        percent = QuestionСoefficient.objects.filter(user = user, quiz = Quiz.objects.get(course = value, name__contains = 'Тренинг'), status = 1)
        percent = percent.filter(coefficient__gte = 23).count() / percent.count() * 100
        
        return round(percent)
    except:
        
        return 0

@register.filter
def decodeDesignImage(data, is_safe=True):
    return mark_safe(data)

class CheckUserPermissions(UserPassesTestMixin):
    def test_func(self):
        return (True if not self.request.user.groups.filter(name='manager').exists() else False)
    
    def handle_no_permission(self):
        return redirect('managementapp:users')

class CourseList(CheckUserPermissions, ListView):
    model = UserRegisteredCourse
    template_name = 'learningapp/home.html'
    context_object_name = 'object_list'

    def get_queryset(self, **kwargs):
        return (
            UserRegisteredCourse.objects
            .filter(user = self.request.user)
            .exclude(timefinish = None)
            .select_related('course')
            .order_by('-id'))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context

class SelectCourse(CheckUserPermissions, DetailView):
    model = Course
    context_object_name = 'object'
    template_name = 'learningapp/select course.html'
    
    def get_object(self):
        return get_object_or_404(Course, slug = self.kwargs['course_slug'])
        
    def post(self, request, **kwargs):
                
        if request.POST.get("form_type") == 'learningtest':
            
            curr_quiz = Quiz.objects.get(course__slug = self.kwargs['course_slug'], name__contains = 'Тренинг')

            last_quiz_attempt, created_quiz_attempt = LearningQuizAttempt.objects.get_or_create(
                quiz = curr_quiz,
                user = self.request.user,
                grade = 0,
                status = Status.objects.get(name = 'В процессе'),
            )
            if created_quiz_attempt == True:
                quizbanks = QuizBankSettings.objects.filter(quiz = curr_quiz)
                bulk_list = []
                sum_questions = Question.objects.none()
                for bank in quizbanks:
                    if bank.tag.all().first():
                        questions = Question.objects.filter(questions_bank__id = bank.bank.id, status = 1, tag__name = bank.tag.all().first())
                    else:
                        questions = Question.objects.filter(questions_bank__id = bank.bank.id, status = 1)
                    last_quiz_attempt.questions.add(*questions.order_by('?')[:bank.qty])
                    sum_questions = sum_questions | questions                
                
                upd = LearningQuizAttemptQuestions.objects.filter(learningquizattempt = last_quiz_attempt).first()
                upd.see_question = False
                upd.save()
                bulk_questions = Question.objects.filter(pk__in = sum_questions)
                status_approved = Status.objects.get(name = 'Утвержден')
                for question in bulk_questions:
                    if not QuestionСoefficient.objects.filter(user = self.request.user, quiz = curr_quiz, question = question, status = status_approved).exists():
                        bulk_list.append(QuestionСoefficient(user = self.request.user, quiz = curr_quiz, question = question, status = status_approved))
                QuestionСoefficient.objects.bulk_create(bulk_list)
            
            return redirect('learningapp:learningtest', course_slug = self.kwargs['course_slug'], quiz_slug = curr_quiz.slug, quizattempt_id = last_quiz_attempt.id)
                    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['course_slug'] = self.kwargs['course_slug']
        context['register_course'] = self.request.user.userregisteredcourse_set.get(course__slug = self.kwargs['course_slug'])
        context['npa'] = Upload.objects.filter(course__slug = self.kwargs['course_slug'], description__contains = 'НПА').exists()
        context['lec'] = Upload.objects.filter(course__slug = self.kwargs['course_slug'], description__contains = 'Лекция').exists()

        return context

class ExamTest(CheckUserPermissions, ListView):
    model = LearningQuizAttempt
    context_object_name = 'object_list'
    paginate_by = 1
    template_name = 'learningapp/examtest.html'
    __start_time = None
    __checked_page = list()

    def get_queryset(self, **kwargs):
        return (
            LearningQuizAttempt.objects
            .select_related('user')
            .prefetch_related('questions')
            .get(pk=self.kwargs['quizattempt_id'])
            .questions
            .order_by()
        )

    def post(self, request, *args, **kwargs):
        if 'page' in self.request.GET:
            page_num = self.request.GET['page']
        else:
            page_num = 1
        if request.POST.getlist('answeroption') != []:

templates/learningapp/questionslist.html
{% extends 'base learning.html' %}
{% block title %}Вопросы{% endblock %}
{% load static %}

{% block content %}
<div style="background-color: #E2EBF6;">
    <nav class="bootcontainer">
        <div id="hide-des-div" class="row">
            <div class="column50">
                <ul class="breadcrumb" style="margin-top: 0; margin-bottom: 0; background: #E2EBF6;">
                    <li><a href="/">Главная</a></li>
                    <li><a href="{% url 'learningapp:courselist' %}">Курсы</a></li>
                    <li><a href="{% url 'learningapp:selectcourse' course_slug %}">Курс</a></li>
                    <li>Поиск вопросов</li>
                </ul>
            </div>
            <div class="column50" style="margin-left: auto; margin-right: 0px;">
                <div style="padding-top: 17px; text-align:  right;">
                    <a href="{% url 'managementapp:about' %}" style="color: #000; text-decoration: none;">
                        <p style="display: inline; padding-left: 17px;">О портале</p>
                    </a>
                    <a href="{% url 'managementapp:support' %}" style="color: #000; text-decoration: none;">
                        <p style="display: inline; padding-left: 15px;">Техническая поддержка</p>
                    </a>
                    <a href="/media/Инструкция Пользователя.pdf" style="color: #000; text-decoration: none;">
                        <p style="display: inline; padding-left: 15px;">Инструкция</p>
                    </a>                
                </div>
            </div>
        </div>
        <div id="hide-mob-div" class="topnav">
            <ul>
                <li><a href="{% url 'learningapp:courselist' %}">Курсы</a></li>
                <li><a href="{% url 'learningapp:selectcourse' course_slug %}">Курс</a></li>
                <li>Поиск вопросов</li>
            </ul>
            <div id="myLinks">
                <a href="{% url 'managementapp:about' %}" style="color: #000; text-decoration: none;">О портале</a>
                <a href="{% url 'managementapp:support' %}" style="color: #000; text-decoration: none;">Техническая поддержка</a>
                <a href="/media/Инструкция Пользователя.pdf" style="color: #000; text-decoration: none;">Инструкция</a> 
            </div>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i>
            </a>
        </div> 
    </nav>

</div>
<div id="popup_hd">
    <div id="popup_helpdesk"><br>
        Контакты технической поддержки<br><br>
        Электронная почта: support@sdo-vot.ru<br>
        Тел: +7(495) 320-88-07<br><br>
        <a href="#" class="close">Закрыть окно</a>
    </div>
</div>
<div class="bootcontainer padding-010010">
    <h2 id="hide-des-div">Поиск вопросов по курсу: {{ course.full_name }}</h2>
    <p id="hide-mob-div" style="font-weight: bold;">Поиск вопросов по курсу: {{ course.full_name }}</p>
    <p>Осталось попыток: {{ register_course.vot_qty }}</p> 
    <br>
    <input class="search" type="text" id="myInput" onkeyup="myFunctionFilter()" placeholder="Поиск ..." title="Type in a name">
    <br>
    <ul class="ulsearch" id="myUL">
        {% for obj in object_list %}
        <li>
            <a href="{% url 'learningapp:selectquestion' course_slug obj.id %}">{{ obj.text }}</a>
        </li>  
        {% endfor %}    
    </ul>
</div>
<script type="text/javascript" src="{% static 'learningapp/js/filter.js'%}"></script>
{% endblock %}

templates/learningapp/report.html
{% extends 'base learning.html' %}
{% block title %}Отчета{% endblock %}
{% load static %}

{% block content %}
<div style="background-color: #E2EBF6;">
    <nav class="bootcontainer">
        <div id="hide-des-div" class="row">
            <div class="column50">
                <ul class="breadcrumb" style="margin-top: 0; margin-bottom: 0; background: #E2EBF6;">
                    <li><a href="/">Главная</a></li>
                    <li><a href="{% url 'learningapp:courselist' %}">Курсы</a></li>
                    <li><a href="{% url 'learningapp:selectcourse' course_slug %}">Курс</a></li>
                    <li><a href="{% url 'learningapp:quizattempts' course_slug %}">Попытки</a></li>
                    <li>Отчет</li>
                </ul>
            </div>
            <div class="column50" style="margin-left: auto; margin-right: 0px;">
                <div style="padding-top: 17px; text-align:  right;">
                    <a href="{% url 'managementapp:about' %}" style="color: #000; text-decoration: none;">
                        <p style="display: inline; padding-left: 17px;">О портале</p>
                    </a>
                    <a href="{% url 'managementapp:support' %}" style="color: #000; text-decoration: none;">
                        <p style="display: inline; padding-left: 15px;">Техническая поддержка</p>
                    </a>
                    {% if template == 'shgi' %}
                        <a href="/media/Инструкция Пользователя.pdf" style="color: #000; text-decoration: none;">
                            <p style="display: inline; padding-left: 15px;">Инструкция</p>
                        </a>
                    {% endif %}                 
                </div>
            </div>
        </div>
        <div id="hide-mob-div" class="topnav">
            <ul>
                <li><a href="{% url 'learningapp:selectcourse' course_slug %}">Курс</a></li>
                <li><a href="{% url 'learningapp:quizattempts' course_slug %}">Попытки</a></li>
                <li>Отчет</li>
            </ul>
            <div id="myLinks">
                <a href="{% url 'managementapp:about' %}" style="color: #000; text-decoration: none;">О портале</a>
                <a href="{% url 'managementapp:support' %}" style="color: #000; text-decoration: none;">Техническая поддержка</a>
                {% if template == 'shgi' %}
                    <a href="/media/Инструкция Пользователя.pdf" style="color: #000; text-decoration: none;">
                        <p style="display: inline; padding-left: 15px;">Инструкция</p>
                    </a>
                {% endif %} 
            </div>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i>
            </a>
        </div> 
    </nav>

</div>
<div id="margin-top-15" class="examtest" style="min-height: 440px; margin-bottom: 150px;">
    <table border="1" class="mob-att-table-rep">
        <tr>
            <th style="width: 1rem;">
                {% if not 'expert' in template %}
                    <img src="{% static 'managementapp/css/шгич.png' %}" style="max-width: 13em;">
                {% else %}
                    <img src="{% static 'managementapp/css/expert-clear.png' %}" style="max-width: 4em;">
                {% endif %}
            </th>
            <th>
                Область: {{ object.quiz.course.full_name }}<br>
                Организация: {{ extend_user.department }}<br>
                ФИО: {{ object.user.last_name }} {{ object.user.first_name }} {{ extend_user.middle_name }}
            </th>
            <th>
                Дата: {{ object.timefinish }}<br>
                Итоговая оценка: 
                    {% if object|percent_result >= 90 %}
                        Cдан
                    {% else %}
                        Не сдан
                    {% endif %}
                <br>
                ({{ object.grade|floatformat }} из {{ object|report_max_grade }})
            </th>
        </tr>        
    </table>
    <table border="1" class="mob-att-table-rep">
        <tr>
        <th>№</th>
        <th>Вопрос</th>
        <th>Выбранный ответ</th>
        <th>Правильный ответ</th>
        </tr>
        {% for q in attempt_questions %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ q.text }}</td>
                <td>
                    {% for a in q.id|attempt_answers:object.id %}
                        <!-- {% if not forloop.first and forloop.last %}
                            {{ forloop.counter }}
                        {% endif %} -->
                        {% if a.weight != 0 %}
                            <label style="color: rgb(14, 202, 14);"> {{ a.text }}</label><br><br>
                        {% else %}
                            <label style="color: red;"> {{ a.text }}</label><br><br>
                        {% endif %}
                    {% endfor %}
                </td>
                <td>
                    {% for a in q.answer_set.all %}
                        {% if a.weight != 0 %}
                            <label> {{ a.text }}</label><br><br>
                        {% endif %}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
        </table>
</div>

{% endblock %}

templates/learningapp/select course.html
{% extends 'base learning.html' %}
{% block title %}Курс{% endblock %}

{% block content %}
<div style="background-color: #E2EBF6;">
    <nav class="bootcontainer">
        <div id="hide-des-div" class="row">
            <div class="column50">
                <ul class="breadcrumb" style="margin-top: 0; margin-bottom: 0; background: #E2EBF6;">
                    <li><a href="/">Главная</a></li>
                    <li><a href="{% url 'learningapp:courselist' %}">Курсы</a></li>
                    <li>Курс</li>
                </ul>
            </div>
            <div class="column50" style="margin-left: auto; margin-right: 0px;">
                <div style="padding-top: 17px; text-align:  right;">
                    <a href="{% url 'managementapp:about' %}" style="color: #000; text-decoration: none;">
                        <p style="display: inline; padding-left: 17px;">О портале</p>
                    </a>
                    <a href="{% url 'managementapp:support' %}" style="color: #000; text-decoration: none;">
                        <p style="display: inline; padding-left: 15px;">Техническая поддержка</p>
                    </a>
                    <a href="/media/Инструкция Пользователя.pdf" style="color: #000; text-decoration: none;">
                        <p style="display: inline; padding-left: 15px;">Инструкция</p>
                    </a>                
                </div>
            </div>
        </div>
        <div id="hide-mob-div" class="topnav">
            <ul>
                <li><a href="/">Главная</a></li>
                <li><a href="{% url 'learningapp:courselist' %}">Курсы</a></li>
                <li>Курс</li>
            </ul>
            <div id="myLinks">
                <a href="{% url 'managementapp:about' %}" style="color: #000; text-decoration: none;">О портале</a>
                <a href="{% url 'managementapp:support' %}" style="color: #000; text-decoration: none;">Техническая поддержка</a>
                <a href="/media/Инструкция Пользователя.pdf" style="color: #000; text-decoration: none;">Инструкция</a> 
            </div>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i>
            </a>
        </div> 
    </nav>

</div>
<div id="popup_hd">
    <div id="popup_helpdesk"><br>
        Контакты технической поддержки<br><br>
        Электронная почта: support@sdo-vot.ru<br>
        Тел: +7(495) 320-88-07<br><br>
        <a href="#" class="close">Закрыть окно</a>
    </div>
</div>
<div id="margin-top-15" class="examtest mb-textcenter" style="min-height: 440px;">
    <div id="rowoff" class="row">
        <div id="column-off" class="column50">
            <h2 style="margin-bottom: 10px; margin-top: 0px;">{{ object.full_name }}</h2>
        </div>
        <div id="column-off" class="column50 mb-textcenter" style="text-align: right;">
            <a href="{% url 'learningapp:courselist' %}" class="btn width70" style="width: 70%;">На предыдущую страницу</a> 
        </div>
    </div>
    <div id="hide-mob-div">
        <br>        
    </div>
    <hr>
    <div id="hide-des-div">
        <br><br>        
    </div>
    <div id="rowoff" class="row">
        {% if messages %}
            {% for message in messages %}
                <p{% if message.tags %} style="color: red; text-align: center;" class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        {% else %}
            <div id="hide-des-div">
                <br><br><br>        
            </div>
        {% endif %}
        <div id="column-off" class="column30">
            <div id="hide-des-div">
                <br><br>        
            </div>
            <h2>Состав Курса</h2>
        </div>
        <div id="column-off" class="column30" style="text-align: center;">
            <p style="font-weight: bold;">
                Шаг 1 <a href="#zatemnenie2"><i class='fa fa-question-circle' style='color: #228fdb; font-size: 20px;'></i></a>
            </p>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% if object.bank_training %}
                    <a class="btn width70" href="{% url 'learningapp:learninglist' course_slug %}" style="width: 80%;">Тренинг</a>  
                {% else %}
                    <button class="btn width77" type="submit" name="form_type" value="learningtest" style="width: 80%;">Тренинг</button>  
                {% endif %}
            </form>
            <div id="zatemnenie2">
                <div id="okno">
                    Тренинг<br><br>
                    Обучение в режиме тренинга это  метод активного обучения направленный на устранение пробелов знаний <br><br>
                    <a href="#" class="close">Закрыть окно</a>
                </div>
            </div>
        </div>
        <div id="column-off" class="column30" style="text-align: center;">
            <p style="font-weight: bold;">
                Шаг 2 <a href="#zatemnenie3"><i class='fa fa-question-circle' style='color: #228fdb; font-size: 20px;'></i></a>
            </p>
            <a class="btn width70" href="{% url 'learningapp:quizattempts' course_slug %}" style="width: 80%;">Проверка знаний</a>  
            <div id="zatemnenie3">
                <div id="okno">
                    Проверка знаний<br><br>
                    Аналог тестирования в Ростехнадзоре<br><br><br>
                    <a href="#" class="close">Закрыть окно</a>
                </div>
            </div>
        </div>
    </div>
    <div id="hide-des-div">
        <br><br>        
    </div>
    <br>
    <hr>
    <div id="rowoff" class="row">
        <div id="column-off" class="column25">
            <div id="hide-des-div">
                <br>        
            </div>
            <h2>Дополнительные модули</h2>
        </div>
        <div class="column25" style="text-align: center;">
            {% if register_course.vot and register_course.vot_qty > 0 %}
            <p style="font-weight: bold;">Вопрос-Ответ</p>
                <a href="{% url 'learningapp:questionslist' course_slug %}" class="btn width70" style="width: 70%;">Поиск ответов</a> 
            {% endif %}
        </div>
        <div id="column-off" class="column25" style="text-align: center;">
            {% if lec %}
                <p style="font-weight: bold;">Лекции и презентации</p>
                <a href="{% url 'learningapp:lec' course_slug %}" class="btn width70" style="width: 70%;">Перейти к изучению</a>
            {% endif %}  
        </div>
        <div id="column-off" class="column25" style="text-align: center;">
            {% if npa %}
                <p style="font-weight: bold;">Библиотека НПА</p>
                <a href="{% url 'learningapp:npa' course_slug %}" class="btn width70" style="width: 70%;">Просмотреть</a> 
            {% endif %}
        </div>
    </div>
    <div id="hide-mob-div">
        <br><br>        
    </div>
</div>
{% endblock %}