cloitLMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('learning/', include('learningapp.urls')),
    path('', include('managementapp.urls')),
    path('adm/', include('administratorapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

managementapp/urls.py
from django.urls import path
from . import views
from managementapp.views import *
from django.contrib.auth.decorators import login_required

app_name = 'managementapp'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about', views.About, name='about'),
    path('login', LogInView.as_view(), name='login'),
    path('support', Support.as_view(), name='support'),
    path('supportcards', login_required(SupportCards.as_view()), name='supportcards'),
    path('logout', login_required(views.logout_user), name='logout'),
    path('registration', login_required(UsersRegistration.as_view()), name='registration'),
    path('edituser/<int:user_id>', login_required(EditUser.as_view()), name='edituser'),
    path('users', login_required(UsersList.as_view()), name='users'),
    path('managers', login_required(ManagersList.as_view()), name='managers'),
    path('usercourses/<int:user_id>/activeuser', login_required(ActiveUser.as_view()), name='activeuser'),
    path('usercourses/<int:user_id>', login_required(UserCourses.as_view()), name='usercourses'),
    path('usercourses/<int:user_id>/bestreport/<int:course_id>', login_required(BestReport.as_view()), name='bestreport'),
    path('usercourses/<int:user_id>/activecourse/<int:course_id>', login_required(ActiveCourse.as_view()), name='activecourse'),
    path('usercourses/<int:user_id>/deletecourse/<int:course_id>', login_required(DeleteCourse.as_view()), name='deletecourse'),
    path('usercourses/<int:user_id>/activecourse/<int:course_id>/statistics', login_required(CourseStatistics.as_view()), name='statistics'),
    path('addnewuser', login_required(UsersList.as_view()), name='addnewuser'),
    path('usercourse/<int:user_id>/addcourse', login_required(AddCourse.as_view()), name='addcourse'),
]

templates/about.html
{% extends 'base.html' %}
{% block title %}О портале{% endblock %}

{% block content %}

<div class="examtest" style="min-height: 440px;">
    <br><br><br>
    <div>

        <p>Сервис обучения и подготовки «Школа главного инженера» — это универсальный инструмент позволяющий в короткие сроки выучить материал и успешно сдать экзамен.</p>
        <p>Вы можете пройти подготовку в режиме тренинга и проверить свои знания в интерфейсах аналогичных Единому порталу тестирования Ростехнадзора.</p>
        <p>В текущей версии «Школы Главного Инженера» Вы можете подготовить себя и свой персонал к аттестации в Ростехнадзоре* по направлениям:</p>
        <p>- Аттестация руководителей и специалистов (постановление Правительства РФ №1365);</p>
        <p>- Проверка знаний норм и правил в области энергетического надзора (группа электробезопасности).</p>
        <br><br>
        <p>*вопросы соответствуют размещенным на сайте Ростехнадзора.</p>
        <br><br><br><br><br><br>
    </div>
    <div style="text-align: center;">
        <a class="button" href="{% url 'managementapp:home' %}">Вернуться на главную страницу</a>
    </div>
</div>

{% endblock %}

templates/base learning.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'examapp/css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="/media/icon.ico">
    {% comment %} <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'> {% endcomment %}
    <script src='https://www.google.com/recaptcha/api.js?render=6LfkYW0eAAAAAExou1PUJwUC6XT7nv1ecjk_x-hl'></script>
<title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <div class="bootcontainer header">
            <div class="row">
                <div class="column30" style="padding-top: 17px; padding-left: 13px;">
                    <a href="/" style="color: #fff; text-decoration: none;">
                        <img id="pic-em" src="{% static 'managementapp/css/шги.png' %}" style="max-width: 13em;">
                        <!-- <img id="pic-em" src="{% static 'managementapp/css/exp.png' %}" style="height: 20%;"> -->
                    </a>
                </div>
                <div class="column70" style="text-align: right; padding-top: 20px;">
                    {% if request.user.is_authenticated %}
                        {% if request.user|check_kaiten_messages %}
                            <div class="row">
                                <div class="column60"></div>
                                <div class="column5" style="padding-right: 5px;">
                                    <a href="{% url 'managementapp:support' %}">
                                        <img src="{% static 'managementapp/pic/support.png' %}" style="width: 3em;">
                                    </a>
                                </div>
                                <div class="column20" style="text-align: left;">
                                    <p style="margin-top: 7px; margin-bottom: 0px;">+7(495) 320-88-07</p>
                                    <p style="margin-top: 0px;">support@sdo-vot.ru</p>
                                </div>
                                <div class="column5" style="padding-left: 20px;">
                                    <div class="dropdown">
                                        <img class="dropbtn" src="{% static 'managementapp/pic/lkdot.png' %}" style="width: 3em;">
                                        <div class="dropdown-content" style="text-align: left;">
                                            <p style="color: black; padding-left: 16px;">{{ user.first_name }} {{ user.last_name }}:</p>
                                            <a href="{{ user|check_home_page }}">Личный кабинет</a>
                                            <a href="{% url 'managementapp:supportcards' %}">Сообщения<label style="font-size: 10px;">&#128308;</label></a>
                                            <a href="{% url 'managementapp:logout' %}">Выход</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="row">
                                <div class="column60"></div>
                                <div class="column5" style="padding-right: 5px;">
                                    <a href="{% url 'managementapp:support' %}">
                                        <img src="{% static 'managementapp/pic/support.png' %}" style="width: 3em;">
                                    </a>
                                </div>
                                <div class="column20" style="text-align: left;">
                                    <p style="margin-top: 7px; margin-bottom: 0px;">+7(495) 320-88-07</p>
                                    <p style="margin-top: 0px;">support@sdo-vot.ru</p>
                                </div>
                                <div class="column5" style="padding-left: 20px;">
                                    <div class="dropdown">
                                        <img class="dropbtn" src="{% static 'managementapp/pic/lk.png' %}" style="width: 3em;">
                                        <div class="dropdown-content" style="text-align: left;">
                                            <p style="color: black; padding-left: 16px;">{{ user.first_name }} {{ user.last_name }}:</p>
                                            <a href="{{ user|check_home_page }}">Личный кабинет</a>
                                            <a href="{% url 'managementapp:supportcards' %}">Мои Заявки в ТП</a>
                                            <a href="{% url 'managementapp:logout' %}">Выход</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% else %}
                        <a class="button-white-white" style="color: white; font-weight: bold;" href="{% url 'managementapp:login' %}">Войти</a>
                    {% endif %}                 
                </div>                
            </div>
        </div>
    </header>
    <main>
        {% block content %}{% endblock %} 
    </main>
</body>
<script type="text/javascript" src="{% static 'examapp/js/mobilenav.js'%}"></script>
</html>

templates/base manager.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'managementapp/css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="/media/icon.ico">
    <script type="text/javascript" src="{% static 'managementapp/js/jquery.min.js'%}"></script>
    {% comment %} <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'> {% endcomment %}
    <script src='https://www.google.com/recaptcha/api.js?render=6LfkYW0eAAAAAExou1PUJwUC6XT7nv1ecjk_x-hl'></script>
    <style type="text/css" media="print">
        .no-print { display: none; }
    </style>
<title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <div class="bootcontainer header">
            <div class="row">
                <div class="column30" style="padding-top: 17px; padding-left: 13px;">
                    <a href="/" style="color: #fff; text-decoration: none;">
                        <img id="pic-em" src="{% static 'managementapp/css/шги.png' %}" style="max-width: 13em;">
                        <!-- <img id="pic-em" src="{% static 'managementapp/css/exp.png' %}" style="height: 20%;"> -->
                    </a>
                </div>
                <div class="column70" style="text-align: right; padding-top: 20px;">
                    {% if request.user.is_authenticated %}
                        {% if request.user|check_kaiten_messages %}
                            <div class="row">
                                <div class="column60"></div>
                                <div class="column5" style="padding-right: 5px;">
                                    <a href="{% url 'managementapp:support' %}">
                                        <img src="{% static 'managementapp/pic/support.png' %}" style="width: 3em;">
                                    </a>
                                </div>
                                <div class="column20" style="text-align: left;">
                                    <p style="margin-top: 7px; margin-bottom: 0px;">+7(495) 320-88-07</p>
                                    <p style="margin-top: 0px;">support@sdo-vot.ru</p>
                                </div>
                                <div class="column5" style="padding-left: 20px;">
                                    <div class="dropdown">
                                        <img class="dropbtn" src="{% static 'managementapp/pic/lkdot.png' %}" style="width: 3em;">
                                        <div class="dropdown-content" style="text-align: left;">
                                            <p style="color: black; padding-left: 16px;">{{ user.first_name }} {{ user.last_name }}:</p>
                                            <a href="{{ user|check_home_page }}">Личный кабинет</a>
                                            <a href="{% url 'managementapp:supportcards' %}">Сообщения<label style="font-size: 10px;">&#128308;</label></a>
                                            <a href="{% url 'managementapp:logout' %}">Выход</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="row">
                                <div class="column60"></div>
                                <div class="column5" style="padding-right: 5px;">
                                    <a href="{% url 'managementapp:support' %}">
                                        <img src="{% static 'managementapp/pic/support.png' %}" style="width: 3em;">
                                    </a>
                                </div>
                                <div class="column20" style="text-align: left;">
                                    <p style="margin-top: 7px; margin-bottom: 0px;">+7(495) 320-88-07</p>
                                    <p style="margin-top: 0px;">support@sdo-vot.ru</p>
                                </div>
                                <div class="column5" style="padding-left: 20px;">
                                    <div class="dropdown">
                                        <img class="dropbtn" src="{% static 'managementapp/pic/lk.png' %}" style="width: 3em;">
                                        <div class="dropdown-content" style="text-align: left;">
                                            <p style="color: black; padding-left: 16px;">{{ user.first_name }} {{ user.last_name }}:</p>
                                            <a href="{{ user|check_home_page }}">Личный кабинет</a>
                                            <a href="{% url 'managementapp:supportcards' %}">Мои Заявки в ТП</a>
                                            <a href="{% url 'managementapp:logout' %}">Выход</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% else %}
                        <a class="button-white-white" style="color: white; font-weight: bold;" href="{% url 'managementapp:login' %}">Войти</a>
                    {% endif %}                 
                </div>                
            </div>
        </div>
    </header>
    <main>
        {% block content %}{% endblock %} 
    </main>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'managementapp/css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="/media/icon.ico">
    {% comment %} <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'> {% endcomment %}
    <script src='https://www.google.com/recaptcha/api.js?render=6LfkYW0eAAAAAExou1PUJwUC6XT7nv1ecjk_x-hl'></script>
<title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <div class="bootcontainer header">
            <div class="row">
                <div class="column30" style="padding-top: 17px; padding-left: 13px;">
                    <a href="/" style="color: #fff; text-decoration: none;">
                        <img id="pic-em" src="{% static 'managementapp/css/шги.png' %}" style="max-width: 13em;">
                        <!-- <img id="pic-em" src="{% static 'managementapp/css/exp.png' %}" style="height: 20%;"> -->
                    </a>
                </div>
                <div class="column70" style="text-align: right; padding-top: 20px;">
                    {% if request.user.is_authenticated %}
                        {% if request.user|check_kaiten_messages %}
                            <div class="row">
                                <div class="column60"></div>
                                <div class="column5" style="padding-right: 5px;">
                                    <a href="{% url 'managementapp:support' %}">
                                        <img src="{% static 'managementapp/pic/support.png' %}" style="width: 3em;">
                                    </a>
                                </div>
                                <div class="column20" style="text-align: left;">
                                    <p style="margin-top: 7px; margin-bottom: 0px;">+7(495) 320-88-07</p>
                                    <p style="margin-top: 0px;">support@sdo-vot.ru</p>
                                </div>
                                <div class="column5" style="padding-left: 20px;">
                                    <div class="dropdown">
                                        <img class="dropbtn" src="{% static 'managementapp/pic/lkdot.png' %}" style="width: 3em;">
                                        <div class="dropdown-content" style="text-align: left;">
                                            <p style="color: black; padding-left: 16px;">{{ user.first_name }} {{ user.last_name }}:</p>
                                            <a href="{{ user|check_home_page }}">Личный кабинет</a>
                                            <a href="{% url 'managementapp:supportcards' %}">Мои Заявки в ТП<label style="font-size: 10px;">&#128308;</label></a>
                                            <a href="{% url 'managementapp:logout' %}">Выход</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="row">
                                <div class="column60"></div>
                                <div class="column5" style="padding-right: 5px;">
                                    <a href="{% url 'managementapp:support' %}">
                                        <img src="{% static 'managementapp/pic/support.png' %}" style="width: 3em;">
                                    </a>
                                </div>
                                <div class="column20" style="text-align: left;">
                                    <p style="margin-top: 7px; margin-bottom: 0px;">+7(495) 320-88-07</p>
                                    <p style="margin-top: 0px;">support@sdo-vot.ru</p>
                                </div>
                                <div class="column5" style="padding-left: 20px;">
                                    <div class="dropdown">
                                        <img class="dropbtn" src="{% static 'managementapp/pic/lk.png' %}" style="width: 3em;">
                                        <div class="dropdown-content" style="text-align: left;">
                                            <p style="color: black; padding-left: 16px;">{{ user.first_name }} {{ user.last_name }}:</p>
                                            <a href="{{ user|check_home_page }}">Личный кабинет</a>
                                            <a href="{% url 'managementapp:supportcards' %}">Сообщения</a>
                                            <a href="{% url 'managementapp:logout' %}">Выход</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% else %}
                        <a class="button-white-white" style="color: white; font-weight: bold;" href="{% url 'managementapp:login' %}">Войти</a>
                    {% endif %}                 
                </div>                
            </div>
        </div>
    </header>
    <main>
        {% block content %}{% endblock %} 
    </main>
    <footer id="footer">
        <div class="bootcontainer">
            <div class="row">
                <div class="column30">
                    <div class="row" style="padding-top: 15px;">
                        <div class="column20">
                            <img src="{% static 'examapp/css/resources/img/favicon_exam.png' %}" style="width: 3em;">
                        </div>
                        <div class="column80">
                            <a href="https://www.gosnadzor.ru/" style="color: #000; text-decoration: none;" target="_blank">
                                <p>Роcтехнадзор</p>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="column40">
                    <div class="row">
                        <div class="column20" style="padding-top: 15px; margin-right: 20px;">
                            <img src="{% static 'examapp/css/resources/img/shgi.png' %}" style="width: 5em;">
                        </div>
                        <div class="column80" style="padding-top: 7px;">
                            <a href="https://sdovot.ru/" style="color: #000; text-decoration: none;" target="_blank">
                                <p>Школа главного инженера</p>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="column30">
                    <div class="row">
                        <div class="column20" style="padding-top: 15px;">
                            <img src="{% static 'examapp/css/resources/img/gov-4.png' %}" style="width: 4em;">
                        </div>
                        <div class="column80">
                            <a href="http://pravo.gov.ru" style="color: #000; text-decoration: none;" target="_blank">
                                <p>Официальный интернет-портал правовой информации</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>        
    </footer>
</body>
<script type="text/javascript" src="{% static 'examapp/js/mobilenav.js'%}"></script>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}ШГИ{% endblock %}
{% load static %}

{% block content %}
<div style="background-color: #E2EBF6;">
    <nav class="bootcontainer">
        <div id="hide-des-div" class="row">
            <div class="column50">
                <ul class="breadcrumb" style="margin-top: 0; margin-bottom: 0; background: #E2EBF6;">
                    <li style="color: #E2EBF6;">Домашняя</li>
                </ul>
            </div>
            <div class="column50" style="margin-left: auto; margin-right: 0px;">
                <div style="padding-top: 17px; text-align:  right;">
                    <a href="{% url 'managementapp:about' %}" style="color: #000; text-decoration: none;">
                        <p style="display: inline; padding-left: 17px;">О портале</p>
                    </a>
                </div>
            </div>
        </div>
        <div id="hide-mob-div" class="topnav">
            <ul>
                <li style="color: #e9ebee;">Домашняя</li>
            </ul>
            <div id="myLinks">
                <a href="{% url 'managementapp:about' %}" style="color: #000; text-decoration: none;">О портале</a>
                <a href="{% url 'managementapp:support' %}" style="color: #000; text-decoration: none;">Техническая поддержка</a>
                <a href="" style="color: #000; text-decoration: none;">Инструкция обучающегося</a> 
            </div>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i>
            </a>
        </div> 
    </nav>

</div>
<div id="popup_hd">
    <div id="popup_helpdesk"><br>
        Контакты технической поддержки<br><br>
        Электронная почта: support@sdo-vot.ru<br>
        Тел: +7(495) 320-88-07<br><br>
        <a href="#" class="close">Закрыть окно</a>
    </div>
</div>
<div id="margin-top-15" class="bootcontainer15">
    <div id="rowoff" class="row">
        <div id="column-off" class="column30">
            <div class="boxelement">               
                <h2 style="text-align: center; margin-top: 0px;">Перечень курсов</h2>
                <div id="hide-des-div">
                    <hr style="border-color: #C6DAED;">        
                </div>                
                <div class="row">
                    <div class="column20" style="text-align: center;">
                        <img style="width: 3em;" src="{% static 'managementapp/pic/doc.png' %}">
                    </div>
                    <div class="column80">
                        <a href="/media/Промышленная безопасность.pdf" style="color: #000; text-decoration: none;" target="_blank">
                            <p style="margin-top: 8px;">Промышленная безопасность</p>
                        </a>
                    </div>
                </div><br><br>
                <div class="row">
                    <div class="column20" style="text-align: center;">
                        <img style="width: 3em;" src="{% static 'managementapp/pic/doc.png' %}">
                    </div>
                    <div class="column80">
                        <a href="/media/Энергобезопасность.pdf" style="color: #000; text-decoration: none;" target="_blank">
                            <p style="margin-top: 8px;">Энергобезопасность</p>
                        </a>
                    </div>
                </div><br><br>
                <div class="row">
                    <div class="column20" style="text-align: center;">
                        <img style="width: 3em;" src="{% static 'managementapp/pic/doc.png' %}">
                    </div>
                    <div class="column80">
                        <a href="/media/Прочие курсы.pdf" style="color: #000; text-decoration: none;" target="_blank">
                            <p style="margin-top: 8px;">Прочие</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div id="column-off" class="column30">
            <div class="boxelement">
                <div id="hide-mob-div">
                    <br><hr>        
                </div> 
                <h2 style="text-align: center; margin-top: 0px;">Информация</h2>
                <div id="hide-des-div">
                    <hr style="border-color: #C6DAED;">        
                </div>
                <div class="row">
                    <div class="column20" style="text-align: center;">
                        <img style="width: 3em;" src="{% static 'managementapp/pic/doc.png' %}">
                    </div>
                    <div class="column80">
                        <a href="/media/Обновления.pdf" style="color: #000; text-decoration: none;" target="_blank">
                            <p style="margin-top: 8px;">Обновленные курсы</p>
                        </a>
                    </div>
                </div><br><br>
                <div class="row">
                    <div class="column20" style="text-align: center;">
                        <img style="width: 3em;" src="{% static 'managementapp/pic/doc.png' %}">
                    </div>
                    <div class="column80">
                        <a href="#popup_sl" style="color: #000; text-decoration: none;">
                            <p style="margin-top: 8px;">Отдел продаж</p>
                        </a>
                        <div id="popup_sl">
                            <div id="popup_sales">
                                <p style="font-weight: bold;">Отдел продаж:</p>

                                Приемная тел. +7 495 240 53 25, эл.почта: sale-vot@sdo-vot.ru<br><br>

                                <p style="font-weight: bold;">Отдел продаж Учебные центры:</p>

                                Менеджер УЦ   тел.   +7-495-320-32-88, эл.почта: zln@sdo-vot.ru<br><br>

                                <p style="font-weight: bold;">Отдел продаж Организации эксплуатирующие ОПО:</p>

                                тел. +7(495) 255-57-79, эл. почта: vtn@sdo-vot.ru<br>

                                тел. +7 (495) 125 02 32, эл. почта: nda@sdo-vot.ru<br><br>
                                
                                <a href="#" class="close">Закрыть окно</a>
                            </div>
                        </div>
                    </div>
                </div><br><br>
                <div class="row">
                    <div class="column20" style="text-align: center;">
                        <img style="width: 3em;" src="{% static 'managementapp/pic/doc.png' %}">
                    </div> 
                    <div class="column80">
                        <a href="{% url 'managementapp:support' %}" style="color: #000; text-decoration: none;"><p>Техническая поддержка</p></a>
                    </div>
                </div>                
            </div>
        </div>
        <div id="column-off" class="column30">
            <div class="boxelement">
                <div id="hide-mob-div">
                    <br><hr>        
                </div> 
                <h2 style="text-align: center; margin-top: 0px;">Инструкции</h2>
                <div id="hide-des-div">
                    <hr style="border-color: #C6DAED;">        
                </div>
                <div class="row">
                    <div class="column20" style="text-align: center;">
                        <img style="width: 3em;" src="{% static 'managementapp/pic/doc.png' %}">
                    </div>
                    <div class="column80">
                        <a href="/media/Инструкция администратора.pdf" style="color: #000; text-decoration: none;" target="_blank">
                            <p style="margin-top: 8px;">Инструкция администратора</p>
                        </a>
                    </div>
                </div>
                <br><br>
                <div class="row">
                    <div class="column20" style="text-align: center;">
                        <img style="width: 3em;" src="{% static 'managementapp/pic/doc.png' %}">
                    </div>
                    <div class="column80">
                        <a href="/media/Инструкция обучающегося.pdf" style="color: #000; text-decoration: none;" target="_blank">
                            <p style="margin-top: 8px;">Инструкция обучающегося</p>
                        </a>
                    </div>
                </div>
                <br><br>
                <div class="row">
                    <div class="column20" style="text-align: center;">
                        <img style="width: 3em;" src="{% static 'managementapp/pic/doc.png' %}">
                    </div>
                    <div class="column80">
                        <a href="/media/Памятка по тренингу.pdf" style="color: #000; text-decoration: none;" target="_blank">
                            <p style="margin-top: 8px;">Памятка по тренингу</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="hide-mob-div">
    <br><br><br>        
</div>
{% endblock %}