administratorapp/urls.py
from django.urls import path
from . import views
from administratorapp.views import *
from django.contrib.auth.decorators import login_required

app_name = 'administratorapp'
urlpatterns = [
    path('managerlist', login_required(ManagerList.as_view()), name='managerlist'),
    path('managerlist/<int:user_id>/activeuser', login_required(ActiveUser.as_view()), name='activeuser'),
]

cloitLMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('learning/', include('learningapp.urls')),
    path('', include('managementapp.urls')),
    path('adm/', include('administratorapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

managementapp/urls.py
from django.urls import path
from . import views
from managementapp.views import *
from django.contrib.auth.decorators import login_required

app_name = 'managementapp'
urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about', views.About, name='about'),
    path('login', LogInView.as_view(), name='login'),
    path('support', Support.as_view(), name='support'),
    path('supportcards', login_required(SupportCards.as_view()), name='supportcards'),
    path('logout', login_required(views.logout_user), name='logout'),
    path('registration', login_required(UsersRegistration.as_view()), name='registration'),
    path('edituser/<int:user_id>', login_required(EditUser.as_view()), name='edituser'),
    path('users', login_required(UsersList.as_view()), name='users'),
    path('managers', login_required(ManagersList.as_view()), name='managers'),
    path('usercourses/<int:user_id>/activeuser', login_required(ActiveUser.as_view()), name='activeuser'),
    path('usercourses/<int:user_id>', login_required(UserCourses.as_view()), name='usercourses'),
    path('usercourses/<int:user_id>/bestreport/<int:course_id>', login_required(BestReport.as_view()), name='bestreport'),
    path('usercourses/<int:user_id>/activecourse/<int:course_id>', login_required(ActiveCourse.as_view()), name='activecourse'),
    path('usercourses/<int:user_id>/deletecourse/<int:course_id>', login_required(DeleteCourse.as_view()), name='deletecourse'),
    path('usercourses/<int:user_id>/activecourse/<int:course_id>/statistics', login_required(CourseStatistics.as_view()), name='statistics'),
    path('addnewuser', login_required(UsersList.as_view()), name='addnewuser'),
    path('usercourse/<int:user_id>/addcourse', login_required(AddCourse.as_view()), name='addcourse'),
]

managementapp/models.py
from django.db import models
from django.db.models.deletion import CASCADE, PROTECT
from django.contrib.auth.models import User
from django.db.models.fields import CharField
import datetime
from django.utils import timezone
from examapp.models import *

class Subscription(models.Model):
    manager = models.ForeignKey(User, related_name='+', on_delete=models.PROTECT, verbose_name='Менеджер')
    user = models.ForeignKey(User, related_name='+', blank=True,  null=True, on_delete=models.PROTECT, verbose_name='Пользователь')
    course = models.ForeignKey(Course, blank=True,  null=True, on_delete=PROTECT, verbose_name='Курс')
    qty = models.IntegerField(default=0, verbose_name='Кол-во подписок')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    subtype = models.CharField(max_length=255, verbose_name='Тип подписки')

    def __str__(self):
        return str(self.id)

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

managementapp/views.py
from email import message_from_binary_file
from email.headerregistry import Group
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect, request, Http404, JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, TemplateView, View
from django.core.mail import EmailMessage, send_mass_mail, send_mail, BadHeaderError
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.template.defaulttags import register
from datetime import date, datetime, timedelta, timezone
from django.contrib.auth.base_user import BaseUserManager
from django.db.models import Sum, Q
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth import login, authenticate
from openpyxl import load_workbook, Workbook
from openpyxl.drawing.image import Image
from openpyxl.styles import Alignment
from openpyxl.utils import get_column_letter
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.mixins import UserPassesTestMixin
from cloitLMS.settings import BASE_DIR
from .models import *
from examapp.models import *
from learningapp.models import *
from learningapp.views import get_learning_time, get_studied_questions, question_count, get_percent
from django.utils.formats import localize
import json
import requests
import re
import time
import docx

symbols = (u"abcdefghijklmnoprstuvwxyzABCDEFGHIJKLMNOPRSTUVWXYZ.-_@1234567890",
        u"123456789012345678901234512345678901234567890123450000ABCDEFGHIJ")
tr = {ord(a):ord(b) for a, b in zip(*symbols)} 

def user_message(login, password, first_name, middle_name, path):
    message = (
        'Уважаемый ' + first_name + ' ' + middle_name + '!\n\n' +
        'Вам предоставлен доступ к сервису обучения и тренинга «Школа главного инженера»\n\n' +
        
        'Для доступа к Вашему личному кабинету Вам необходимо перейти по ссылке https://' + path + '/login\n' +
        'Логин: ' + login + '\n' +
        'Пароль: ' + password + '\n\n' +
        'Инструкция пользователя доступна по ссылке: https://' + path + '/media/Инструкция%20обучающегося.pdf\n' +
        'В случае если у Вас возникнут вопросы - Вы можете обратиться в техническую поддержку:\n' +
        '- Email: support@sdo-vot.ru\n' +
        '- Tel: +7(495) 320-88-07 ( с 06:00 по 23:00 по Московскому времени)\n' +

        'Обращаем Ваше внимание, что логин и пароль вы можете скопировать из данного письма и вставить в окне авторизации.'
        )
    print(message)
    return message

@register.filter
def qty_sum(user):
    qty = Subscription.objects.filter(manager = user).aggregate(Sum('qty'))
    return 0 if qty['qty__sum'] is None else qty['qty__sum']

@register.filter
def check_attempt_exist(value, user):
    return LearningQuizAttempt.objects.filter(user = user, quiz = Quiz.objects.get(course = value, name__contains = 'Проверка знаний'), status_id = 3).exists()

@register.filter
def last_login(user):
    return User.objects.get(pk = user).last_login

@register.filter
def check_home_page(user):
    if user.groups.filter(name='manager').exists():
        return str('/users')
    elif user.is_staff:
        return str('/adm/managerlist')
    else:
        return str('/learning')

@register.filter
def split_parent_course(value, course):
    return value.replace(course, '')

@register.filter
def qty_month_sum(user):
    today = datetime.datetime.today()
    datem = datetime.datetime(today.year, today.month, 1)
    qty = Subscription.objects.filter(manager = user, date__gte = datem, qty__lt = 0).count()
    return 0 if qty is None else qty

@register.filter
def check_kaiten_messages(user):
    headers = {
        'Accept': 'application/json', 
        'Content-Type': 'application/json', 
        'Authorization': 'Bearer 680c3c04-c773-48b7-ba1f-9a5c9951ca95'
    }
    cards = HelpDeskCards.objects.filter(user = user)
    for card in reversed(cards):
        url = f"https://alexeyomich.kaiten.ru/api/latest/cards/{card.card}/comments"
        r = requests.get(url, headers=headers)
        if r.status_code == 429:
            time.sleep(1)
            r = requests.get(url, headers=headers)
        if r.status_code == 200:
            if r.json() and r.json()[-1]['author']['full_name'] != 'Guest' and r.json()[-1]['created'] > card.update:

                return True
    
    return False

def About(request):
    return render(request, 'about.html')

def logout_user(request):
    logout(request)
    return redirect('managementapp:login')

class CheckManagerPermissions(UserPassesTestMixin):
    
    def test_func(self):
        return self.request.user.groups.filter(name = 'manager').exists()
    
    def handle_no_permission(self):
        return redirect('learningapp:courselist')

class CheckSalerPermissions(UserPassesTestMixin):
    
    def test_func(self):
        return self.request.user.groups.filter(name = 'saler').exists()
    
    def handle_no_permission(self):
        return redirect('learningapp:courselist')
    
class Home(TemplateView):
    template_name = 'home.html'
        
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        
        return context

class Support(TemplateView):
    template_name = 'support.html'

    def post(self, request, *args, **kwargs):
        
        if request.POST.get("form_type") == 'send_email':

            description = f"ФИО: {request.POST.get('name')}\n\nЛогин: {request.POST.get('login')}\n\nEmail: {request.POST.get('email')}\n\nСообщение: {request.POST.get('text')}"

            url = "https://alexeyomich.kaiten.ru/api/latest/cards"
            
            data = { 
                "title": "Заявка с Формы ШГИ", 
                "board_id": 468128, 
                "description": description,
                "responsible_id": 417435, 
                "external_id": (self.request.user.id if self.request.user.is_authenticated else ''), 
                "properties": {}
            }
        
            headers = {
                'Accept': 'application/json', 
                'Content-Type': 'application/json', 
                'Authorization': 'Bearer 9f4ff229-aee5-43f2-a765-18e93a818c7e'
            }
            
            r = requests.post(url, data=json.dumps(data), headers=headers)
            if self.request.user.is_authenticated:
                try:
                    HelpDeskCards.objects.create(user = self.request.user, card = int(r.json()['id']), update = r.json()['created'])

                    return redirect('managementapp:supportcards')
                
                except:
                    pass

        return redirect('managementapp:home')

@register.filter
def card_get_id(card):
    return card.split(' ')[1]

def support_card_detail(card, update):
    url = f"https://alexeyomich.kaiten.ru/api/latest/cards/{card}"
    headers = {
        'Accept': 'application/json', 
        'Content-Type': 'application/json', 
        'Authorization': 'Bearer 680c3c04-c773-48b7-ba1f-9a5c9951ca95'
    }
    r = requests.get(url, headers=headers)
    if r.status_code == 429:
        time.sleep(1)
        r = requests.get(url, headers=headers)
    if r.json()['comment_last_added_at'] and r.json()['comment_last_added_at'] > update:
        text = f"Заявка: {r.json()['id']} от {datetime.datetime.strftime(datetime.datetime.fromisoformat(r.json()['created']), '%d.%m.%Y %H:%M')}; Статус: {r.json()['column']['title']}<br>{(r.json()['description']).split('Сообщение: ')[1]}<br><br>Непрочитанное сообщение!"
    else:
        text = f"Заявка: {r.json()['id']} от {datetime.datetime.strftime(datetime.datetime.fromisoformat(r.json()['created']), '%d.%m.%Y %H:%M')}; Статус: {r.json()['column']['title']}<br>{(r.json()['description']).split('Сообщение: ')[1]}<br>"
    
    return text

def support_card_comments(card, user):
    url = f"https://alexeyomich.kaiten.ru/api/latest/cards/{card}/comments"
    headers = {
        'Accept': 'application/json', 
        'Content-Type': 'application/json', 
        'Authorization': 'Bearer 680c3c04-c773-48b7-ba1f-9a5c9951ca95'
    }
    r = requests.get(url, headers=headers)
    comments = []
    comments_dict = {}
    for comment in r.json():
        if comment['author']['full_name'] == 'Guest':
            comments_dict[comment['id']] = f"{user}:<br>{comment['text']}"
        else:
            comments_dict[comment['id']] = f"{comment['author']['full_name']}:<br>{comment['text']}"
    for key in sorted(comments_dict):
        comments.append(comments_dict[key])
    hdc = HelpDeskCards.objects.get(card = card, user = user)
    try:
        if hdc.update < r.json()[-1]['created']:
            hdc.update = r.json()[-1]['created']
            hdc.save()
    except:
        pass
    return comments

class SupportCards(ListView):
    model = HelpDeskCards
    template_name = 'support cards.html'

    def get_queryset(self, *args, **kwargs):
        if self.request.GET.get('card'):
            return HelpDeskCards.objects.get(card = self.request.GET.get('card'))
        else:
            cards = HelpDeskCards.objects.filter(user = self.request.user)
            cards_list = []
            for card in cards:
                cards_list.append(support_card_detail(card.card, card.update))
            return cards_list
    
    def post(self, request, *args, **kwargs):
        if request.POST.get("form_type") == 'send' and request.POST.get('text'):
            url = f"https://alexeyomich.kaiten.ru/api/latest/cards/{self.request.GET.get('card')}/comments"
            headers = {
                'Accept': 'application/json', 

templates/managementapp/addcourse.html
{% extends 'base manager.html' %}
{% load static %}
{% block title %}Создать пользователя{% endblock %}
 
{% block content %}
<div style="background-color: #E2EBF6;">
    <nav class="bootcontainer">
        <div class="row">
            <div class="column50">
                <ul class="breadcrumb" style="margin-top: 0; margin-bottom: 0; background: #E2EBF6;">
                    <li><a href="{% url 'managementapp:users' %}">Пользователи</a></li>
                    <li><a href="{% url 'managementapp:usercourses' user_id %}">Курсы</a></li>
                    <li>Запись на курсы</li>
                </ul>
            </div>
            <div class="column50" style="text-align: right;">
                <div style="padding-top: 17px;">
                    <a href="{% url 'managementapp:about' %}" style="color: #000; text-decoration: none;">
                        <p style="display: inline; padding-left: 17px;">О портале</p>
                    </a>
                    <a href="{% url 'managementapp:support' %}" style="color: #000; text-decoration: none;">
                        <p style="display: inline; padding-left: 15px;">Техническая поддержка</p>
                    </a>
                    <div id="popup_hd">
                        <div id="popup_helpdesk"><br>
                            Контакты технической поддержки<br><br>
                            Электронная почта: support@sdo-vot.ru<br>
                            Тел: +7(495) 320-88-07<br><br>
                            <a href="#" class="close">Закрыть окно</a>
                        </div>
                    </div>            
                </div>
            </div>
        </div>
    </nav>

</div>
<br>
<div class="examtest" style="min-height: 440px; max-width: 900px;;">
    <form method="post" class="multipart/form-data">
        {% csrf_token %}
        <h2 style="text-align: center;">Записать на курс</h2><hr>
        <div style="text-align: center;">
            <div class="row">
                <div class="column40" style="text-align: left; padding-left: 25%;">
                    <p>Область:</p>
                </div>
                <div class="column60" style="text-align: left;">
                    <select id="selectdisplay" class="selectdisplay combo-a minimal" data-nextcombo=".combo-b" style="width: 70%;">
                        <option value="0" selected disabled></option>
                        {% for obj in course_types %}
                            {% if obj.name == 'Эксперты' %}
                                <option value="{{ obj.name }}" data-id="{{ obj.id }}" data-option="-1">{{ obj.name }}</option>
                            {% else %}
                                <option value="{{ obj.id }}" data-id="{{ obj.id }}" data-option="-1">{{ obj.name }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row">
                <div class="column40" style="text-align: left; padding-left: 25%;">
                    <p>Курс:</p>
                </div>
                <div class="column60" style="text-align: left;">
                    <select name="courseid" class="combo-b minimal" data-nextcombo=".combo-c" style="width: 70%;" disabled>
                        {% for obj in object_list %}
                            <option value="{{ obj.id }}" data-id="{{ obj.id }}" data-option="{{ obj.course_type.id }}">{{ obj.name }}</option>
                        {% endfor %}
                    </select>                
                </div>        
            </div>
            <div  class="row">
                <div id="elbezrole1" class="column40" style="text-align: left; padding-left: 25%;">
                    <p>Категория по напряжению:</p>
                </div>
                <div id="elbezrole2" class="column60" style="text-align: left;">
                    <select name="categoryid" class="combo-c minimal" data-nextcombo=".combo-d" style="width: 70%;" disabled>
                        {% for obj in parent_course %}
                            <option value="{{ obj.id }}" data-id="{{ obj.id }}" data-option="{{ obj.parent.id }}">{{ obj.name|split_parent_course:obj.parent.name }}</option>
                        {% endfor %}
                    </select>
                </div>        
            </div><br>
            <!-- <div id="votcheck" style="display: none;" class="custom-control custom-checkbox mb-4">
                <input type="checkbox" class="custom-control-input" name="enrolattempt" id="defaultContactFormCopy">
                <label class="custom-control-label" for="defaultContactFormCopy">Вопрос-Ответ</label>
            </div> -->
            <div id="zadachicheck" style="display: none;" class="custom-control custom-checkbox mb-4">
                <input type="checkbox" class="custom-control-input" name="zadachi" id="defaultContactFormCopy">
                <label class="custom-control-label" for="defaultContactFormCopy">Задачи</label>
            </div>
        </div><br><br><br><br>
        <hr>
        <div style="text-align: center;">
            <button type="submit" class="button-white" style="width: 30%;">Записать</button>
        </div>
    </form>
</div>
<script type="text/javascript" src="{% static 'managementapp/js/addcourse.js'%}"></script>
<script type="text/javascript" src="{% static 'managementapp/js/selecthide2.js'%}"></script>

{% endblock %}

templates/managementapp/usercourses.html
{% extends 'base manager.html' %}
{% block title %}Запись на курсы{% endblock %}
{% load static %}

{% block content %}
<div style="background-color: #E2EBF6;">
    <nav class="bootcontainer">
        <div class="row">
            <div class="column50">
                <ul class="breadcrumb" style="margin-top: 0; margin-bottom: 0; background: #E2EBF6;">
                    <li><a href="{% url 'managementapp:users' %}">Пользователи</a></li>
                    <li>Курсы</li>
                </ul>
            </div>
            <div class="column50" style="text-align: right;">
                <div style="padding-top: 17px;">
                    <a href="{% url 'managementapp:about' %}" style="color: #000; text-decoration: none;">
                        <p style="display: inline; padding-left: 17px;">О портале</p>
                    </a>
                    <a href="{% url 'managementapp:support' %}" style="color: #000; text-decoration: none;">
                        <p style="display: inline; padding-left: 15px;">Техническая поддержка</p>
                    </a>          
                </div>
            </div>
        </div>
    </nav>
</div><br>
<div class="bootcontainer15">
    <div class="row">
        <div class="column25">
            <div class="box">
                <p>Доступные подписки: {{ request.user|qty_sum }} шт.</p>
                <p style="padding-right: 10px;">Использовано подписок в текущем месяце: {{ request.user|qty_month_sum }} шт.</p>
            </div>
        </div>
        <div class="column25" style="padding-left: 15px;">
            <p>Обучающийся: {{ curr_user.last_name }} {{ curr_user.first_name }} {{ curr_user.extendinguserfields.middle_name }}</p>
            <p>Организация: {{ curr_user.extendinguserfields.department }}</p>
            <p>Электронная почта: {{ curr_user.email }}</p>
        </div>
        <div class="column25">

        </div>
        <div class="column25">
        
        </div>
    </div><br><br>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}<br>
    <form method="post" class="multipart/form-data">
        {% csrf_token %} 
        <div class="row">
            <div class="column15" align="center">
                <!-- <a style="max-width: 75%;" class="button" href="{% url 'managementapp:addcourse' user_id %}">Записать на курс</a> -->
                <button type="button" class="button" name="form_type" value="edituser" style="padding-left: 10px; padding-right: 10px;" onclick="location.href='{% url 'managementapp:addcourse' user_id %}';">Записать на курс</button>
            </div>
            <div class="column15" align="center">
                <button type="submit" class="button" name="form_type" value="edituser" style="padding-left: 10px; padding-right: 10px;">Ред. пользователя</button>
            </div>
            <div class="column15" align="center">
                <button type="submit" class="button" name="form_type" value="senduser" style="padding-left: 10px; padding-right: 10px;">Отправить пароль <i class='fa fa-question-circle' title="Выберете одного или нескольких пользователей и нажмите кнопку 'Отправить пароли', В результате выбранным пользователям будет направлено приглашение для подготовки в Школе главного инженера, в письме пользователю будут указаны ссылка для перехода в систему подготовки, а также логин и пароль пользователя" style='color: white; font-size: 20px;'></i></button>           
            </div>
            <div class="column55" align="center">

            </div>
        </div>
    </form>
    <br>
    <div>
        <table id="table2" class="text-center" align="center" width="100%">
            <thead>
                <tr>
                    <th style="text-align: center;">Курс</th>
                    <th style="text-align: center;">Модуль "вопрос-ответ"</th>
                    <th style="text-align: center;">Активировать</th>
                    <th style="text-align: center;">Дата активации</th>
                    <th style="text-align: center;">Дата закрытия</th>
                    <th style="text-align: center;">Статистика</th>
                    <th style="text-align: center;">Удалить</th>                    
                </tr>                
            </thead>
            <tbody>
                {% for obj in object_list %}
                    <tr>
                        <td>{{ obj.course.full_name }}</td>
                        <td>
                            {% if obj.vot %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z"/>
                                </svg>
                            {% else %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-dash-lg" viewBox="0 0 16 16">
                                    <path fill-rule="evenodd" d="M2 8a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11A.5.5 0 0 1 2 8Z"/>
                                </svg>
                            {% endif %}
                        </td>
                        <td>
                            {% if obj.status == None %}
                                <form action="{% url 'managementapp:activecourse' user_id obj.course.id %}" onsubmit="activeCourse(this);return false;">
                                    <label class="switch">
                                        <button>
                                            <span class="slider-none"></span>   
                                        </button>
                                    </label>                            
                                </form>
                            {% elif obj.course.id|check_course_end:user_id %}
                                <label class="switch">
                                    <span class="slider-on"></span>
                                </label>
                            {% else %}
                                <form action="{% url 'managementapp:activecourse' user_id obj.course.id %}" onsubmit="extendCourse(this);return false;">
                                    <label class="switch">
                                        <button>
                                            <span class="slider-off"></span>   
                                        </button>
                                    </label>                            
                                </form>
                            {% endif %}

                        </td>
                        <td>{{ obj.timeactive|date:"d.m.Y" }}</td>
                        <td>{{ obj.timefinish|date:"d.m.Y" }}</td>
                        <td>
                            {% if obj.status != None %}
                                <a href="{% url 'managementapp:statistics' user_id obj.course.id %}">Статистика по курсу</a>
                            {% endif %}
                            {% if obj.course|check_attempt_exist:curr_user %}
                                <br><br>
                                <a href="{% url 'managementapp:bestreport' user_id obj.course.id %}">Результат лучшего теста</a>
                            {% endif %}
                        </td>
                        <td>
                            {% if obj.status == None %}
                                <a href="{% url 'managementapp:deletecourse' user_id obj.course.id %}">удалить</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}                
            </tbody>
        </table>
        <div style="text-align: center;">                        
            {% if paginator.count > 10 %}
                <div class="pagination">
                    {% if page_obj.number > 3 %}
                        <a href="?page=1">1</a>
                        {% if page_obj.number > 4 %}
                            <a href="#" style="pointer-events: none; cursor: default;">...</a>
                        {% endif %}
                    {% endif %}
    
                    {% for p in paginator.page_range %}
                        {% if page_obj.number == p %}
                            <a href="?page={{ p }}" class="active">{{ p }}</a>
                        {% elif p > page_obj.number|add:'-3' and p < page_obj.number|add:'3' %}
                            {% if p in checked_page %}
                                <a style="color: black; background-color: #E7E6E7;" href="?page={{ p }}">{{ p }}</a>
                            {% else %}
                                <a href="?page={{ p }}">{{ p }}</a>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
    
                    {% if page_obj.number < paginator.num_pages|add:'-3' %}
                        <a href="#" style="pointer-events: none; cursor: default;">...</a>
                        {% if paginator.num_pages in checked_page %}
                            <a style="color: black; background-color: #E7E6E7;" href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                        {% else %}
                            <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                        {% endif %}
                    {% elif page_obj.number < paginator.num_pages|add:'-2' %}
                        {% if paginator.num_pages in checked_page %}
                            <a style="color: black; background-color: #E7E6E7;" href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                        {% else %}
                            <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                        {% endif %}
                    {% endif %}
                </div>
            {% else %}
                <div class="pagination">
                    {% for p in paginator.page_range %}
                        {% if page_obj.number == p %}
                            <a href="?page={{ p }}" class="active">{{ p }}</a>
                        {% else %}
                            <a href="?page={{ p }}">{{ p }}</a>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
</div>

<script type="text/javascript" src="{% static 'managementapp/js/extendcourse.js'%}"></script>
{% endblock %}